name: 'Test LocalStack GitHub Actions Login'

on: [ push, pull_request ]

jobs:
  build:
    name: ğŸš§ Build the GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: âš¡ï¸ Checkout the repository
        uses: actions/checkout@v3
      - name: ğŸš€ Install dependencies
        run: |
          yarn install --pure-lockfile
      - name: ğŸ‰ Build the project
        run: |
          yarn run all

  test:
    name: ğŸŒ Test the GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: âš¡ï¸ Checkout the repository
        uses: actions/checkout@v3

      - name: â˜ï¸ Start LocalStack
        run: |
          pip install pyopenssl -U
          docker pull localstack/localstack-pro:1.4
          pip install localstack
          DNS_ADDRESS=0 localstack start -d
          localstack wait -t 30
          pip install awscli-local[ver1]
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

      - name: ğŸ¤” Login to LocalStack
        uses: ./
        with:
          email: ${{ secrets.LOCALSTACK_USERNAME }}
          password: ${{ secrets.LOCALSTACK_PASSWORD }}
